modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mixins]]
config = "the_beyond.mixins.json"
[[mixins]]
config = "the_beyond.client.mixins.json"

[[mods]]
enumExtensions="META-INF/enumextensions.json"
modId="the_beyond"
version="0.1.0"
displayName="The Beyond"
authors="YourName"
description='''
A cool mod. Replace this with a real description.
'''

[[dependencies.the_beyond]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.the_beyond]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
